export {default as Navbar} from './Navbar'
export {default as Home} from './Home'
export {default as Statistics} from "./Statistics"
export {default as CTA} from "./CTA"
export {default as Button} from "./Button"
export {default as Contract} from "./Contract"
export {default as Billing} from "./Billing"
export {default as FeAtureCard} from "./FeatureCard"
export {default as Business} from "./Business"